# Generated by Django 2.1.3 on 2019-07-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190705_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='item',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='section',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
