# Generated by Django 2.1.3 on 2019-07-05 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190705_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subsection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Subsection', verbose_name='Подраздел'),
        ),
        migrations.AddField(
            model_name='section',
            name='subsections',
            field=models.ManyToManyField(to='shop.Subsection', verbose_name='Подразделы'),
        ),
        migrations.AlterField(
            model_name='item',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Section', verbose_name='Раздел'),
        ),
    ]
