# Generated by Django 2.1.3 on 2019-07-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190705_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionrelationship',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sectionrelationship',
            name='subsection',
        ),
        migrations.RemoveField(
            model_name='section',
            name='subsections',
        ),
        migrations.AddField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Section', verbose_name='Раздел'),
        ),
        migrations.DeleteModel(
            name='SectionRelationship',
        ),
    ]
