# Generated by Django 2.1.3 on 2019-07-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190705_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='section',
        ),
    ]
