# Generated by Django 2.1.3 on 2019-07-05 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_item_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='subsection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Subsection', verbose_name='Подраздел'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Section', verbose_name='Раздел'),
        ),
    ]
