# Generated by Django 2.1.3 on 2019-07-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190705_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='subsection',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
