# Generated by Django 2.1.3 on 2019-07-08 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190705_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subsection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Subsection', verbose_name='Показать товары из секции'),
        ),
    ]
