# Generated by Django 2.1.3 on 2019-07-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190710_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание товара'),
        ),
    ]
