# Generated by Django 2.1.3 on 2019-07-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart',
            new_name='items',
        ),
    ]
