# Generated by Django 2.1.3 on 2019-07-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20190713_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odereditem',
            options={'verbose_name_plural': 'Заказ'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
