# Generated by Django 2.1.3 on 2019-07-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20190713_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odereditem',
            name='user',
        ),
    ]
